# # NOT DONE!!!
# image: amazonlinux:latest

# pipelines:
#   default:
#     - step:
#         name: Build and Push Docker Image to AWS ECR
#         deployment: test
#         condition:
#           changesets:
#             includePaths:
#               - Dockerfile
#               - config/**
#         # OIDC is a more secure method of managing access to AWS than supplying IAM credentials
#         # See https://cirrostratus.cloud/deploying-cdk-to-aws-using-bitbucket-pipelines-and-oidc
#         # and https://support.atlassian.com/bitbucket-cloud/docs/deploy-on-aws-using-bitbucket-pipelines-openid-connect/
#         oidc: true
#         caches:
#           - pip
#           - node
#         script:
#           - export AWS_REGION=us-west-2
#           - export AWS_ROLE_ARN=$DEV_AWS_OIDC_ROLE_ARN
#           - export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/web-identity-token
#           - echo $BITBUCKET_STEP_OIDC_TOKEN > $(pwd)/web-identity-token

#           # Install Docker and AWS CLI
#           - sudo yum remove awscli
#           - sudo dnf update
#           - sudo dnf install -y docker
#           - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#           - unzip awscliv2.zip
#           - sudo ./aws/install

#           # Authentiate Docker to your ECR registry
#           # Build and tag the Docker image
#           # Push the Docker image to ECR
# options:
#   docker: true